name: Deploy Guard

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check-safety:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Time Window Check
        uses: ./.github/actions/time-window-checker
        with:
          bypass_label: "bypass-time-warnings"
          start_hour_utc: "10"
